version: "3"

services:
  rr_server:
    build:
      context: .
      args:
        USER_UID: ${HOST_UID}
        USER_GID: ${HOST_GID}
    image: ringracer
    #image: siraceyt/ringracers:2.3
    environment:
      - ADVERTISE="Yes"
      #- CHOOSEN_UID=1000
      #- CHOOSEN_GID=1000
    tty: true
    stdin_open: true
    ports:
      - "5029:5029/udp"
    volumes:
      - ./ringracers/data:/home/ringracers/.ringracers
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "./entrypoint.sh monitor"]
      interval: 30s
      start_period: 30s
